import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  restaurant: string;
  description: string;
  rating: number;
  reviews: number;
  preparationTime: string;
  isAvailable: boolean;
  isPopular?: boolean;
  isFeatured?: boolean;
  isNew?: boolean;
  discount?: number;
  tags: string[];
  ingredients: string[];
  allergens: string[];
  nutritionalInfo: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
  };
  spiceLevel: 'mild' | 'medium' | 'hot' | 'extra-hot';
  portionSize: string;
  customizations?: {
    id: string;
    name: string;
    options: { id: string; name: string; price: number }[];
  }[];
}

export interface Restaurant {
  id: string;
  name: string;
  image: string;
  rating: number;
  reviews: number;
  deliveryTime: string;
  deliveryFee: number;
  minimumOrder: number;
  cuisine: string[];
  isOpen: boolean;
  distance: string;
  promoted?: boolean;
}

interface ProductsState {
  items: Product[];
  restaurants: Restaurant[];
  categories: string[];
  featured: Product[];
  trending: Product[];
  dailyDeals: Product[];
  flashSales: Product[];
  loading: boolean;
  searchQuery: string;
  selectedCategory?: string;
  filters: {
    priceRange: [number, number];
    rating: number;
    preparationTime: number;
    spiceLevel: string[];
    dietary: string[];
  };
}

const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Bella Italia',
    image: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg',
    rating: 4.8,
    reviews: 1250,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minimumOrder: 15,
    cuisine: ['Italian', 'Pizza', 'Pasta'],
    isOpen: true,
    distance: '0.8 km',
    promoted: true,
  },
  {
    id: '2',
    name: 'Spice Garden',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    rating: 4.6,
    reviews: 890,
    deliveryTime: '30-40 min',
    deliveryFee: 1.99,
    minimumOrder: 20,
    cuisine: ['Indian', 'Curry', 'Vegetarian'],
    isOpen: true,
    distance: '1.2 km',
  },
  {
    id: '3',
    name: 'Tokyo Sushi',
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg',
    rating: 4.9,
    reviews: 2100,
    deliveryTime: '20-30 min',
    deliveryFee: 3.99,
    minimumOrder: 25,
    cuisine: ['Japanese', 'Sushi', 'Asian'],
    isOpen: true,
    distance: '0.5 km',
  },
  {
    id: '4',
    name: 'Burger Palace',
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    rating: 4.4,
    reviews: 756,
    deliveryTime: '15-25 min',
    deliveryFee: 2.49,
    minimumOrder: 12,
    cuisine: ['American', 'Burgers', 'Fast Food'],
    isOpen: true,
    distance: '1.5 km',
  },
  {
    id: '5',
    name: 'Green Bowl',
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    rating: 4.7,
    reviews: 432,
    deliveryTime: '20-30 min',
    deliveryFee: 1.99,
    minimumOrder: 18,
    cuisine: ['Healthy', 'Salads', 'Vegan'],
    isOpen: true,
    distance: '0.9 km',
  },
  {
    id: '6',
    name: 'Ocean Breeze',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    rating: 4.5,
    reviews: 623,
    deliveryTime: '25-35 min',
    deliveryFee: 3.49,
    minimumOrder: 22,
    cuisine: ['Seafood', 'Mediterranean'],
    isOpen: true,
    distance: '1.8 km',
  },
  {
    id: '7',
    name: 'Taco Fiesta',
    image: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg',
    rating: 4.3,
    reviews: 445,
    deliveryTime: '20-30 min',
    deliveryFee: 2.99,
    minimumOrder: 15,
    cuisine: ['Mexican', 'Tacos', 'Burritos'],
    isOpen: true,
    distance: '1.1 km',
  },
];

const mockProducts: Product[] = [
  // Pizza Category
  {
    id: '1',
    name: 'Margherita Pizza',
    price: 18.99,
    originalPrice: 22.99,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Classic Italian pizza with fresh mozzarella, tomato sauce, and basil leaves on a crispy thin crust.',
    rating: 4.8,
    reviews: 324,
    preparationTime: '15-20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    discount: 17,
    tags: ['vegetarian', 'classic', 'popular'],
    ingredients: ['Mozzarella', 'Tomato Sauce', 'Fresh Basil', 'Olive Oil'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 285,
      protein: 12,
      carbs: 36,
      fat: 10,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: '12 inch',
  },
  {
    id: '11',
    name: 'Pepperoni Supreme',
    price: 21.99,
    originalPrice: 24.99,
    image: 'https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Loaded with premium pepperoni, extra cheese, and Italian herbs on our signature crust.',
    rating: 4.7,
    reviews: 289,
    preparationTime: '18-22 min',
    isAvailable: true,
    isPopular: true,
    discount: 12,
    tags: ['meat', 'popular', 'spicy'],
    ingredients: ['Pepperoni', 'Mozzarella', 'Tomato Sauce', 'Italian Herbs'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 340,
      protein: 16,
      carbs: 38,
      fat: 15,
      fiber: 2,
    },
    spiceLevel: 'medium',
    portionSize: '12 inch',
  },
  {
    id: '12',
    name: 'BBQ Chicken Pizza',
    price: 23.99,
    image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Grilled chicken, BBQ sauce, red onions, and cilantro on a smoky barbecue base.',
    rating: 4.6,
    reviews: 198,
    preparationTime: '20-25 min',
    isAvailable: true,
    tags: ['chicken', 'bbq', 'smoky'],
    ingredients: ['Grilled Chicken', 'BBQ Sauce', 'Red Onions', 'Cilantro', 'Mozzarella'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 365,
      protein: 22,
      carbs: 40,
      fat: 14,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: '12 inch',
  },
  {
    id: '13',
    name: 'Veggie Deluxe',
    price: 20.99,
    image: 'https://images.pexels.com/photos/1049626/pexels-photo-1049626.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Fresh vegetables including bell peppers, mushrooms, olives, and tomatoes.',
    rating: 4.5,
    reviews: 156,
    preparationTime: '16-20 min',
    isAvailable: true,
    tags: ['vegetarian', 'healthy', 'fresh'],
    ingredients: ['Bell Peppers', 'Mushrooms', 'Olives', 'Tomatoes', 'Mozzarella'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 265,
      protein: 11,
      carbs: 35,
      fat: 9,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: '12 inch',
  },
  {
    id: '14',
    name: 'Meat Lovers',
    price: 26.99,
    image: 'https://images.pexels.com/photos/905847/pexels-photo-905847.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Pepperoni, sausage, ham, and bacon on a rich tomato base with extra cheese.',
    rating: 4.8,
    reviews: 267,
    preparationTime: '22-28 min',
    isAvailable: true,
    isPopular: true,
    tags: ['meat', 'hearty', 'protein'],
    ingredients: ['Pepperoni', 'Sausage', 'Ham', 'Bacon', 'Mozzarella'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 420,
      protein: 24,
      carbs: 38,
      fat: 22,
      fiber: 2,
    },
    spiceLevel: 'medium',
    portionSize: '12 inch',
  },
  {
    id: '15',
    name: 'White Truffle Pizza',
    price: 32.99,
    image: 'https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg',
    category: 'Pizza',
    restaurant: 'Bella Italia',
    description: 'Premium white sauce base with truffle oil, wild mushrooms, and arugula.',
    rating: 4.9,
    reviews: 89,
    preparationTime: '25-30 min',
    isAvailable: true,
    isFeatured: true,
    tags: ['premium', 'truffle', 'gourmet'],
    ingredients: ['White Sauce', 'Truffle Oil', 'Wild Mushrooms', 'Arugula', 'Parmesan'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 385,
      protein: 15,
      carbs: 36,
      fat: 20,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: '12 inch',
  },

  // Indian Category
  {
    id: '2',
    name: 'Chicken Tikka Masala',
    price: 16.99,
    image: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Tender chicken pieces in a rich, creamy tomato-based curry sauce with aromatic spices.',
    rating: 4.7,
    reviews: 189,
    preparationTime: '20-25 min',
    isAvailable: true,
    isFeatured: true,
    tags: ['spicy', 'creamy', 'popular'],
    ingredients: ['Chicken', 'Tomatoes', 'Cream', 'Onions', 'Garam Masala'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 420,
      protein: 28,
      carbs: 12,
      fat: 18,
      fiber: 3,
    },
    spiceLevel: 'medium',
    portionSize: 'Regular',
  },
  {
    id: '16',
    name: 'Lamb Biryani',
    price: 22.99,
    image: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Fragrant basmati rice layered with tender lamb, saffron, and traditional spices.',
    rating: 4.8,
    reviews: 234,
    preparationTime: '35-40 min',
    isAvailable: true,
    isPopular: true,
    tags: ['lamb', 'rice', 'aromatic'],
    ingredients: ['Lamb', 'Basmati Rice', 'Saffron', 'Yogurt', 'Biryani Spices'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 520,
      protein: 32,
      carbs: 45,
      fat: 22,
      fiber: 2,
    },
    spiceLevel: 'medium',
    portionSize: 'Large',
  },
  {
    id: '17',
    name: 'Palak Paneer',
    price: 14.99,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Fresh spinach curry with cubes of cottage cheese in a creamy, spiced gravy.',
    rating: 4.6,
    reviews: 167,
    preparationTime: '18-22 min',
    isAvailable: true,
    tags: ['vegetarian', 'spinach', 'healthy'],
    ingredients: ['Spinach', 'Paneer', 'Cream', 'Onions', 'Indian Spices'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 285,
      protein: 16,
      carbs: 8,
      fat: 20,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '18',
    name: 'Tandoori Chicken',
    price: 18.99,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Marinated chicken cooked in a traditional tandoor oven with yogurt and spices.',
    rating: 4.7,
    reviews: 198,
    preparationTime: '25-30 min',
    isAvailable: true,
    tags: ['tandoor', 'grilled', 'protein'],
    ingredients: ['Chicken', 'Yogurt', 'Tandoori Spices', 'Lemon', 'Ginger'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 320,
      protein: 35,
      carbs: 4,
      fat: 16,
      fiber: 1,
    },
    spiceLevel: 'hot',
    portionSize: 'Half Chicken',
  },
  {
    id: '19',
    name: 'Dal Makhani',
    price: 12.99,
    image: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Slow-cooked black lentils in a rich, creamy tomato and butter sauce.',
    rating: 4.5,
    reviews: 145,
    preparationTime: '20-25 min',
    isAvailable: true,
    tags: ['vegetarian', 'lentils', 'comfort'],
    ingredients: ['Black Lentils', 'Butter', 'Cream', 'Tomatoes', 'Spices'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 245,
      protein: 12,
      carbs: 28,
      fat: 10,
      fiber: 8,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '20',
    name: 'Chicken Vindaloo',
    price: 17.99,
    image: 'https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg',
    category: 'Indian',
    restaurant: 'Spice Garden',
    description: 'Fiery Goan curry with chicken, vinegar, and a blend of hot spices.',
    rating: 4.4,
    reviews: 123,
    preparationTime: '22-28 min',
    isAvailable: true,
    tags: ['spicy', 'goan', 'hot'],
    ingredients: ['Chicken', 'Vinegar', 'Red Chilies', 'Garlic', 'Goan Spices'],
    allergens: [],
    nutritionalInfo: {
      calories: 380,
      protein: 30,
      carbs: 8,
      fat: 24,
      fiber: 2,
    },
    spiceLevel: 'extra-hot',
    portionSize: 'Regular',
  },

  // Sushi Category
  {
    id: '3',
    name: 'Salmon Sashimi',
    price: 24.99,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg',
    category: 'Sushi',
    restaurant: 'Tokyo Sushi',
    description: 'Fresh Atlantic salmon, expertly sliced and served with wasabi and pickled ginger.',
    rating: 4.9,
    reviews: 412,
    preparationTime: '10-15 min',
    isAvailable: true,
    isNew: true,
    tags: ['fresh', 'premium', 'healthy'],
    ingredients: ['Fresh Salmon', 'Wasabi', 'Pickled Ginger', 'Soy Sauce'],
    allergens: ['Fish'],
    nutritionalInfo: {
      calories: 180,
      protein: 25,
      carbs: 0,
      fat: 8,
      fiber: 0,
    },
    spiceLevel: 'mild',
    portionSize: '6 pieces',
  },
  {
    id: '5',
    name: 'Dragon Roll',
    price: 19.99,
    image: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
    category: 'Sushi',
    restaurant: 'Tokyo Sushi',
    description: 'Shrimp tempura and cucumber inside, topped with eel and avocado.',
    rating: 4.8,
    reviews: 298,
    preparationTime: '15-20 min',
    isAvailable: true,
    isPopular: true,
    tags: ['tempura', 'eel', 'signature'],
    ingredients: ['Shrimp Tempura', 'Cucumber', 'Eel', 'Avocado', 'Nori'],
    allergens: ['Shellfish', 'Fish', 'Gluten'],
    nutritionalInfo: {
      calories: 340,
      protein: 16,
      carbs: 28,
      fat: 18,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: '8 pieces',
  },
  {
    id: '21',
    name: 'Rainbow Roll',
    price: 22.99,
    image: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
    category: 'Sushi',
    restaurant: 'Tokyo Sushi',
    description: 'California roll topped with assorted fresh fish including tuna, salmon, and yellowtail.',
    rating: 4.7,
    reviews: 267,
    preparationTime: '18-22 min',
    isAvailable: true,
    isFeatured: true,
    tags: ['colorful', 'variety', 'fresh'],
    ingredients: ['Crab', 'Avocado', 'Cucumber', 'Tuna', 'Salmon', 'Yellowtail'],
    allergens: ['Shellfish', 'Fish'],
    nutritionalInfo: {
      calories: 285,
      protein: 18,
      carbs: 24,
      fat: 12,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: '8 pieces',
  },
  {
    id: '22',
    name: 'Spicy Tuna Roll',
    price: 16.99,
    image: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
    category: 'Sushi',
    restaurant: 'Tokyo Sushi',
    description: 'Fresh tuna mixed with spicy mayo, cucumber, and scallions, rolled in nori.',
    rating: 4.6,
    reviews: 189,
    preparationTime: '12-16 min',
    isAvailable: true,
    tags: ['spicy', 'tuna', 'popular'],
    ingredients: ['Tuna', 'Spicy Mayo', 'Cucumber', 'Scallions', 'Nori'],
    allergens: ['Fish', 'Eggs'],
    nutritionalInfo: {
      calories: 220,
      protein: 14,
      carbs: 18,
      fat: 10,
      fiber: 2,
    },
    spiceLevel: 'medium',
    portionSize: '6 pieces',
  },
  {
    id: '23',
    name: 'Chirashi Bowl',
    price: 28.99,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg',
    category: 'Sushi',
    restaurant: 'Tokyo Sushi',
    description: 'Assorted fresh sashimi over seasoned sushi rice with traditional accompaniments.',
    rating: 4.8,
    reviews: 156,
    preparationTime: '15-20 min',
    isAvailable: true,
    tags: ['variety', 'bowl', 'premium'],
    ingredients: ['Assorted Sashimi', 'Sushi Rice', 'Wasabi', 'Pickled Vegetables'],
    allergens: ['Fish'],
    nutritionalInfo: {
      calories: 420,
      protein: 28,
      carbs: 35,
      fat: 16,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: 'Large Bowl',
  },
  {
    id: '24',
    name: 'Miso Soup',
    price: 4.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Tokyo Sushi',
    description: 'Traditional Japanese soup with miso paste, tofu, seaweed, and scallions.',
    rating: 4.4,
    reviews: 234,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['soup', 'traditional', 'light'],
    ingredients: ['Miso Paste', 'Tofu', 'Seaweed', 'Scallions', 'Dashi'],
    allergens: ['Soy'],
    nutritionalInfo: {
      calories: 35,
      protein: 3,
      carbs: 4,
      fat: 1,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: 'Cup',
  },

  // Pasta Category
  {
    id: '4',
    name: 'Truffle Pasta',
    price: 28.99,
    originalPrice: 32.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Bella Italia',
    description: 'Handmade fettuccine with black truffle, parmesan, and cream sauce.',
    rating: 4.6,
    reviews: 156,
    preparationTime: '18-22 min',
    isAvailable: true,
    discount: 12,
    tags: ['premium', 'truffle', 'creamy'],
    ingredients: ['Fettuccine', 'Black Truffle', 'Parmesan', 'Cream', 'Garlic'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 520,
      protein: 18,
      carbs: 45,
      fat: 28,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '25',
    name: 'Carbonara',
    price: 19.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Bella Italia',
    description: 'Classic Roman pasta with eggs, pecorino cheese, pancetta, and black pepper.',
    rating: 4.7,
    reviews: 298,
    preparationTime: '15-18 min',
    isAvailable: true,
    isPopular: true,
    tags: ['classic', 'roman', 'eggs'],
    ingredients: ['Spaghetti', 'Eggs', 'Pecorino', 'Pancetta', 'Black Pepper'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 485,
      protein: 22,
      carbs: 42,
      fat: 24,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '26',
    name: 'Seafood Linguine',
    price: 26.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Ocean Breeze',
    description: 'Fresh linguine with shrimp, mussels, clams in a white wine garlic sauce.',
    rating: 4.8,
    reviews: 187,
    preparationTime: '22-28 min',
    isAvailable: true,
    tags: ['seafood', 'wine', 'garlic'],
    ingredients: ['Linguine', 'Shrimp', 'Mussels', 'Clams', 'White Wine', 'Garlic'],
    allergens: ['Gluten', 'Shellfish'],
    nutritionalInfo: {
      calories: 445,
      protein: 26,
      carbs: 48,
      fat: 16,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '27',
    name: 'Penne Arrabbiata',
    price: 16.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Bella Italia',
    description: 'Spicy tomato sauce with garlic, red chilies, and fresh herbs over penne pasta.',
    rating: 4.5,
    reviews: 167,
    preparationTime: '14-18 min',
    isAvailable: true,
    tags: ['spicy', 'tomato', 'vegetarian'],
    ingredients: ['Penne', 'Tomatoes', 'Garlic', 'Red Chilies', 'Herbs'],
    allergens: ['Gluten'],
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 58,
      fat: 6,
      fiber: 4,
    },
    spiceLevel: 'hot',
    portionSize: 'Regular',
  },
  {
    id: '28',
    name: 'Mushroom Risotto',
    price: 22.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Bella Italia',
    description: 'Creamy arborio rice with wild mushrooms, parmesan, and white wine.',
    rating: 4.6,
    reviews: 134,
    preparationTime: '25-30 min',
    isAvailable: true,
    tags: ['creamy', 'mushrooms', 'rice'],
    ingredients: ['Arborio Rice', 'Wild Mushrooms', 'Parmesan', 'White Wine', 'Butter'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 385,
      protein: 14,
      carbs: 52,
      fat: 14,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '29',
    name: 'Lasagna Bolognese',
    price: 24.99,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'Pasta',
    restaurant: 'Bella Italia',
    description: 'Layers of pasta with rich meat sauce, béchamel, and melted cheese.',
    rating: 4.8,
    reviews: 245,
    preparationTime: '30-35 min',
    isAvailable: true,
    isPopular: true,
    tags: ['layered', 'meat', 'cheese'],
    ingredients: ['Pasta Sheets', 'Ground Beef', 'Béchamel', 'Mozzarella', 'Parmesan'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 565,
      protein: 28,
      carbs: 42,
      fat: 32,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },

  // Burgers Category
  {
    id: '7',
    name: 'Classic Cheeseburger',
    price: 12.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Burger Palace',
    description: 'Juicy beef patty with cheese, lettuce, tomato, and special sauce.',
    rating: 4.4,
    reviews: 567,
    preparationTime: '12-18 min',
    isAvailable: true,
    isPopular: true,
    tags: ['classic', 'beef', 'cheese'],
    ingredients: ['Beef Patty', 'Cheese', 'Lettuce', 'Tomato', 'Bun'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 650,
      protein: 35,
      carbs: 45,
      fat: 35,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '30',
    name: 'BBQ Bacon Burger',
    price: 15.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Burger Palace',
    description: 'Double beef patty with crispy bacon, BBQ sauce, onion rings, and cheddar.',
    rating: 4.6,
    reviews: 423,
    preparationTime: '15-20 min',
    isAvailable: true,
    tags: ['bacon', 'bbq', 'double'],
    ingredients: ['Double Beef Patty', 'Bacon', 'BBQ Sauce', 'Onion Rings', 'Cheddar'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 785,
      protein: 42,
      carbs: 48,
      fat: 48,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '31',
    name: 'Mushroom Swiss Burger',
    price: 14.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Burger Palace',
    description: 'Beef patty topped with sautéed mushrooms, Swiss cheese, and garlic aioli.',
    rating: 4.5,
    reviews: 298,
    preparationTime: '14-18 min',
    isAvailable: true,
    tags: ['mushrooms', 'swiss', 'gourmet'],
    ingredients: ['Beef Patty', 'Sautéed Mushrooms', 'Swiss Cheese', 'Garlic Aioli'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 620,
      protein: 38,
      carbs: 42,
      fat: 32,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '32',
    name: 'Spicy Jalapeño Burger',
    price: 13.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Burger Palace',
    description: 'Beef patty with jalapeños, pepper jack cheese, and chipotle mayo.',
    rating: 4.3,
    reviews: 234,
    preparationTime: '12-16 min',
    isAvailable: true,
    tags: ['spicy', 'jalapeño', 'hot'],
    ingredients: ['Beef Patty', 'Jalapeños', 'Pepper Jack', 'Chipotle Mayo'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 675,
      protein: 36,
      carbs: 44,
      fat: 38,
      fiber: 3,
    },
    spiceLevel: 'hot',
    portionSize: 'Regular',
  },
  {
    id: '33',
    name: 'Veggie Black Bean Burger',
    price: 11.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Green Bowl',
    description: 'House-made black bean patty with avocado, sprouts, and tahini sauce.',
    rating: 4.4,
    reviews: 187,
    preparationTime: '10-14 min',
    isAvailable: true,
    tags: ['vegetarian', 'black bean', 'healthy'],
    ingredients: ['Black Bean Patty', 'Avocado', 'Sprouts', 'Tahini Sauce'],
    allergens: ['Gluten', 'Sesame'],
    nutritionalInfo: {
      calories: 420,
      protein: 18,
      carbs: 52,
      fat: 16,
      fiber: 12,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '34',
    name: 'Fish Burger',
    price: 16.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    category: 'Burgers',
    restaurant: 'Ocean Breeze',
    description: 'Grilled salmon fillet with cucumber, dill sauce, and mixed greens.',
    rating: 4.7,
    reviews: 156,
    preparationTime: '16-20 min',
    isAvailable: true,
    tags: ['fish', 'salmon', 'healthy'],
    ingredients: ['Salmon Fillet', 'Cucumber', 'Dill Sauce', 'Mixed Greens'],
    allergens: ['Fish', 'Gluten', 'Eggs'],
    nutritionalInfo: {
      calories: 485,
      protein: 32,
      carbs: 38,
      fat: 22,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },

  // Healthy Category
  {
    id: '8',
    name: 'Quinoa Power Bowl',
    price: 14.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Healthy',
    restaurant: 'Green Bowl',
    description: 'Nutritious quinoa bowl with roasted vegetables, avocado, and tahini dressing.',
    rating: 4.7,
    reviews: 189,
    preparationTime: '15-20 min',
    isAvailable: true,
    isFeatured: true,
    tags: ['healthy', 'vegan', 'protein'],
    ingredients: ['Quinoa', 'Avocado', 'Roasted Vegetables', 'Tahini', 'Seeds'],
    allergens: ['Sesame'],
    nutritionalInfo: {
      calories: 420,
      protein: 15,
      carbs: 45,
      fat: 18,
      fiber: 12,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '35',
    name: 'Acai Bowl',
    price: 12.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Healthy',
    restaurant: 'Green Bowl',
    description: 'Acai berry smoothie bowl topped with granola, fresh fruits, and coconut.',
    rating: 4.6,
    reviews: 267,
    preparationTime: '8-12 min',
    isAvailable: true,
    isPopular: true,
    tags: ['acai', 'smoothie', 'antioxidants'],
    ingredients: ['Acai', 'Granola', 'Berries', 'Banana', 'Coconut'],
    allergens: ['Nuts'],
    nutritionalInfo: {
      calories: 285,
      protein: 8,
      carbs: 52,
      fat: 8,
      fiber: 10,
    },
    spiceLevel: 'mild',
    portionSize: 'Medium',
  },
  {
    id: '36',
    name: 'Kale Caesar Salad',
    price: 13.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Healthy',
    restaurant: 'Green Bowl',
    description: 'Massaged kale with parmesan, croutons, and house-made caesar dressing.',
    rating: 4.4,
    reviews: 198,
    preparationTime: '10-12 min',
    isAvailable: true,
    tags: ['kale', 'caesar', 'crunchy'],
    ingredients: ['Kale', 'Parmesan', 'Croutons', 'Caesar Dressing'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    nutritionalInfo: {
      calories: 245,
      protein: 12,
      carbs: 18,
      fat: 16,
      fiber: 6,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '37',
    name: 'Buddha Bowl',
    price: 16.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Healthy',
    restaurant: 'Green Bowl',
    description: 'Brown rice, roasted chickpeas, sweet potato, and green goddess dressing.',
    rating: 4.8,
    reviews: 234,
    preparationTime: '12-16 min',
    isAvailable: true,
    tags: ['buddha', 'chickpeas', 'wholesome'],
    ingredients: ['Brown Rice', 'Chickpeas', 'Sweet Potato', 'Green Goddess Dressing'],
    allergens: ['Sesame'],
    nutritionalInfo: {
      calories: 385,
      protein: 14,
      carbs: 58,
      fat: 12,
      fiber: 11,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },
  {
    id: '38',
    name: 'Protein Smoothie',
    price: 8.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Beverages',
    restaurant: 'Green Bowl',
    description: 'Vanilla protein powder, banana, almond butter, and oat milk blend.',
    rating: 4.5,
    reviews: 156,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['protein', 'smoothie', 'post-workout'],
    ingredients: ['Protein Powder', 'Banana', 'Almond Butter', 'Oat Milk'],
    allergens: ['Nuts'],
    nutritionalInfo: {
      calories: 320,
      protein: 25,
      carbs: 28,
      fat: 12,
      fiber: 6,
    },
    spiceLevel: 'mild',
    portionSize: '16 oz',
  },
  {
    id: '39',
    name: 'Grilled Chicken Salad',
    price: 15.99,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    category: 'Healthy',
    restaurant: 'Green Bowl',
    description: 'Grilled chicken breast over mixed greens with cherry tomatoes and balsamic.',
    rating: 4.6,
    reviews: 189,
    preparationTime: '12-15 min',
    isAvailable: true,
    tags: ['chicken', 'protein', 'low-carb'],
    ingredients: ['Grilled Chicken', 'Mixed Greens', 'Cherry Tomatoes', 'Balsamic'],
    allergens: [],
    nutritionalInfo: {
      calories: 285,
      protein: 32,
      carbs: 12,
      fat: 12,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: 'Large',
  },

  // Desserts Category
  {
    id: '9',
    name: 'Chocolate Lava Cake',
    price: 8.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Bella Italia',
    description: 'Warm chocolate cake with molten center, served with vanilla ice cream.',
    rating: 4.9,
    reviews: 445,
    preparationTime: '10-15 min',
    isAvailable: true,
    tags: ['dessert', 'chocolate', 'warm'],
    ingredients: ['Dark Chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 380,
      protein: 6,
      carbs: 45,
      fat: 20,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Individual',
  },
  {
    id: '40',
    name: 'Tiramisu',
    price: 9.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Bella Italia',
    description: 'Classic Italian dessert with coffee-soaked ladyfingers and mascarpone.',
    rating: 4.8,
    reviews: 367,
    preparationTime: '5-8 min',
    isAvailable: true,
    isPopular: true,
    tags: ['italian', 'coffee', 'creamy'],
    ingredients: ['Ladyfingers', 'Mascarpone', 'Coffee', 'Cocoa', 'Marsala'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 425,
      protein: 8,
      carbs: 38,
      fat: 26,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: 'Individual',
  },
  {
    id: '41',
    name: 'Cheesecake',
    price: 7.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Bella Italia',
    description: 'New York style cheesecake with graham cracker crust and berry compote.',
    rating: 4.7,
    reviews: 298,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['cheesecake', 'berries', 'classic'],
    ingredients: ['Cream Cheese', 'Graham Crackers', 'Berries', 'Sugar', 'Vanilla'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 465,
      protein: 9,
      carbs: 42,
      fat: 28,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: 'Slice',
  },
  {
    id: '42',
    name: 'Gelato Trio',
    price: 6.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Bella Italia',
    description: 'Three scoops of artisanal gelato: vanilla, chocolate, and pistachio.',
    rating: 4.6,
    reviews: 234,
    preparationTime: '3-5 min',
    isAvailable: true,
    tags: ['gelato', 'trio', 'cold'],
    ingredients: ['Milk', 'Cream', 'Vanilla', 'Chocolate', 'Pistachios'],
    allergens: ['Dairy', 'Nuts'],
    nutritionalInfo: {
      calories: 285,
      protein: 6,
      carbs: 32,
      fat: 14,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: '3 Scoops',
  },
  {
    id: '43',
    name: 'Mochi Ice Cream',
    price: 5.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Tokyo Sushi',
    description: 'Japanese rice cake filled with premium ice cream in assorted flavors.',
    rating: 4.5,
    reviews: 189,
    preparationTime: '2-3 min',
    isAvailable: true,
    tags: ['mochi', 'japanese', 'ice cream'],
    ingredients: ['Rice Flour', 'Ice Cream', 'Sugar', 'Natural Flavors'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 120,
      protein: 2,
      carbs: 22,
      fat: 3,
      fiber: 0,
    },
    spiceLevel: 'mild',
    portionSize: '3 Pieces',
  },
  {
    id: '44',
    name: 'Churros with Chocolate',
    price: 6.99,
    image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg',
    category: 'Desserts',
    restaurant: 'Taco Fiesta',
    description: 'Crispy fried dough sticks dusted with cinnamon sugar, served with chocolate sauce.',
    rating: 4.4,
    reviews: 167,
    preparationTime: '8-12 min',
    isAvailable: true,
    tags: ['churros', 'chocolate', 'crispy'],
    ingredients: ['Flour', 'Cinnamon', 'Sugar', 'Chocolate Sauce'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 320,
      protein: 4,
      carbs: 48,
      fat: 12,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: '6 Pieces',
  },

  // Beverages Category
  {
    id: '10',
    name: 'Iced Coffee',
    price: 4.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Green Bowl',
    description: 'Cold brew coffee served over ice with your choice of milk.',
    rating: 4.3,
    reviews: 234,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['coffee', 'cold', 'refreshing'],
    ingredients: ['Coffee Beans', 'Ice', 'Milk'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 45,
      protein: 2,
      carbs: 6,
      fat: 1,
      fiber: 0,
    },
    spiceLevel: 'mild',
    portionSize: '16 oz',
  },
  {
    id: '45',
    name: 'Fresh Orange Juice',
    price: 5.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Green Bowl',
    description: 'Freshly squeezed orange juice packed with vitamin C.',
    rating: 4.6,
    reviews: 189,
    preparationTime: '3-5 min',
    isAvailable: true,
    tags: ['fresh', 'vitamin c', 'citrus'],
    ingredients: ['Fresh Oranges'],
    allergens: [],
    nutritionalInfo: {
      calories: 110,
      protein: 2,
      carbs: 26,
      fat: 0,
      fiber: 0,
    },
    spiceLevel: 'mild',
    portionSize: '12 oz',
  },
  {
    id: '46',
    name: 'Green Smoothie',
    price: 7.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Green Bowl',
    description: 'Spinach, apple, banana, ginger, and coconut water blend.',
    rating: 4.4,
    reviews: 156,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['green', 'healthy', 'detox'],
    ingredients: ['Spinach', 'Apple', 'Banana', 'Ginger', 'Coconut Water'],
    allergens: [],
    nutritionalInfo: {
      calories: 145,
      protein: 3,
      carbs: 35,
      fat: 1,
      fiber: 6,
    },
    spiceLevel: 'mild',
    portionSize: '16 oz',
  },
  {
    id: '47',
    name: 'Matcha Latte',
    price: 6.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Tokyo Sushi',
    description: 'Premium matcha powder whisked with steamed milk and a touch of honey.',
    rating: 4.7,
    reviews: 198,
    preparationTime: '6-8 min',
    isAvailable: true,
    tags: ['matcha', 'japanese', 'antioxidants'],
    ingredients: ['Matcha Powder', 'Milk', 'Honey'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 120,
      protein: 6,
      carbs: 18,
      fat: 3,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: '12 oz',
  },
  {
    id: '48',
    name: 'Mango Lassi',
    price: 5.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Spice Garden',
    description: 'Traditional Indian yogurt drink blended with fresh mango and cardamom.',
    rating: 4.5,
    reviews: 167,
    preparationTime: '4-6 min',
    isAvailable: true,
    tags: ['mango', 'yogurt', 'indian'],
    ingredients: ['Mango', 'Yogurt', 'Cardamom', 'Sugar'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 165,
      protein: 5,
      carbs: 32,
      fat: 3,
      fiber: 2,
    },
    spiceLevel: 'mild',
    portionSize: '12 oz',
  },
  {
    id: '49',
    name: 'Sparkling Water',
    price: 2.99,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    category: 'Beverages',
    restaurant: 'Green Bowl',
    description: 'Refreshing sparkling water with natural fruit flavors.',
    rating: 4.2,
    reviews: 123,
    preparationTime: '1-2 min',
    isAvailable: true,
    tags: ['sparkling', 'refreshing', 'zero calories'],
    ingredients: ['Sparkling Water', 'Natural Flavors'],
    allergens: [],
    nutritionalInfo: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
    },
    spiceLevel: 'mild',
    portionSize: '16 oz',
  },

  // Appetizers Category
  {
    id: '50',
    name: 'Bruschetta',
    price: 8.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Bella Italia',
    description: 'Toasted bread topped with fresh tomatoes, basil, and balsamic glaze.',
    rating: 4.5,
    reviews: 189,
    preparationTime: '8-10 min',
    isAvailable: true,
    tags: ['italian', 'fresh', 'tomatoes'],
    ingredients: ['Bread', 'Tomatoes', 'Basil', 'Balsamic', 'Olive Oil'],
    allergens: ['Gluten'],
    nutritionalInfo: {
      calories: 145,
      protein: 4,
      carbs: 22,
      fat: 5,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: '4 Pieces',
  },
  {
    id: '51',
    name: 'Chicken Wings',
    price: 11.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Burger Palace',
    description: 'Crispy chicken wings tossed in buffalo sauce, served with ranch dip.',
    rating: 4.6,
    reviews: 267,
    preparationTime: '12-15 min',
    isAvailable: true,
    isPopular: true,
    tags: ['wings', 'buffalo', 'spicy'],
    ingredients: ['Chicken Wings', 'Buffalo Sauce', 'Ranch Dressing'],
    allergens: ['Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 385,
      protein: 28,
      carbs: 2,
      fat: 28,
      fiber: 0,
    },
    spiceLevel: 'medium',
    portionSize: '8 Wings',
  },
  {
    id: '52',
    name: 'Guacamole & Chips',
    price: 7.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Taco Fiesta',
    description: 'Fresh avocado dip with lime, cilantro, and jalapeños, served with tortilla chips.',
    rating: 4.4,
    reviews: 198,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['guacamole', 'avocado', 'mexican'],
    ingredients: ['Avocado', 'Lime', 'Cilantro', 'Jalapeños', 'Tortilla Chips'],
    allergens: [],
    nutritionalInfo: {
      calories: 285,
      protein: 4,
      carbs: 28,
      fat: 18,
      fiber: 8,
    },
    spiceLevel: 'medium',
    portionSize: 'Large Bowl',
  },
  {
    id: '53',
    name: 'Calamari Rings',
    price: 12.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Ocean Breeze',
    description: 'Crispy fried squid rings served with marinara sauce and lemon.',
    rating: 4.7,
    reviews: 156,
    preparationTime: '10-12 min',
    isAvailable: true,
    tags: ['seafood', 'crispy', 'mediterranean'],
    ingredients: ['Squid', 'Flour', 'Marinara Sauce', 'Lemon'],
    allergens: ['Gluten', 'Shellfish'],
    nutritionalInfo: {
      calories: 320,
      protein: 18,
      carbs: 24,
      fat: 16,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '54',
    name: 'Samosas',
    price: 6.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Spice Garden',
    description: 'Crispy pastry triangles filled with spiced potatoes and peas.',
    rating: 4.5,
    reviews: 134,
    preparationTime: '8-10 min',
    isAvailable: true,
    tags: ['indian', 'vegetarian', 'crispy'],
    ingredients: ['Pastry', 'Potatoes', 'Peas', 'Indian Spices'],
    allergens: ['Gluten'],
    nutritionalInfo: {
      calories: 185,
      protein: 4,
      carbs: 28,
      fat: 7,
      fiber: 3,
    },
    spiceLevel: 'medium',
    portionSize: '4 Pieces',
  },
  {
    id: '55',
    name: 'Edamame',
    price: 4.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Appetizers',
    restaurant: 'Tokyo Sushi',
    description: 'Steamed young soybeans lightly salted, a healthy Japanese appetizer.',
    rating: 4.3,
    reviews: 167,
    preparationTime: '5-7 min',
    isAvailable: true,
    tags: ['healthy', 'japanese', 'protein'],
    ingredients: ['Edamame Beans', 'Sea Salt'],
    allergens: ['Soy'],
    nutritionalInfo: {
      calories: 95,
      protein: 8,
      carbs: 8,
      fat: 4,
      fiber: 4,
    },
    spiceLevel: 'mild',
    portionSize: 'Bowl',
  },

  // Snacks Category
  {
    id: '56',
    name: 'Sweet Potato Fries',
    price: 6.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Green Bowl',
    description: 'Crispy baked sweet potato fries with a hint of cinnamon and sea salt.',
    rating: 4.5,
    reviews: 198,
    preparationTime: '12-15 min',
    isAvailable: true,
    tags: ['sweet potato', 'healthy', 'crispy'],
    ingredients: ['Sweet Potatoes', 'Cinnamon', 'Sea Salt', 'Olive Oil'],
    allergens: [],
    nutritionalInfo: {
      calories: 165,
      protein: 2,
      carbs: 32,
      fat: 4,
      fiber: 5,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '57',
    name: 'Loaded Nachos',
    price: 9.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Taco Fiesta',
    description: 'Tortilla chips topped with cheese, jalapeños, sour cream, and guacamole.',
    rating: 4.6,
    reviews: 234,
    preparationTime: '8-12 min',
    isAvailable: true,
    isPopular: true,
    tags: ['nachos', 'loaded', 'sharing'],
    ingredients: ['Tortilla Chips', 'Cheese', 'Jalapeños', 'Sour Cream', 'Guacamole'],
    allergens: ['Dairy'],
    nutritionalInfo: {
      calories: 485,
      protein: 12,
      carbs: 42,
      fat: 28,
      fiber: 6,
    },
    spiceLevel: 'medium',
    portionSize: 'Large',
  },
  {
    id: '58',
    name: 'Hummus Platter',
    price: 8.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Ocean Breeze',
    description: 'Creamy hummus served with pita bread, olives, and fresh vegetables.',
    rating: 4.4,
    reviews: 156,
    preparationTime: '5-8 min',
    isAvailable: true,
    tags: ['hummus', 'mediterranean', 'healthy'],
    ingredients: ['Chickpeas', 'Tahini', 'Pita Bread', 'Olives', 'Vegetables'],
    allergens: ['Sesame', 'Gluten'],
    nutritionalInfo: {
      calories: 245,
      protein: 8,
      carbs: 32,
      fat: 10,
      fiber: 7,
    },
    spiceLevel: 'mild',
    portionSize: 'Platter',
  },
  {
    id: '59',
    name: 'Onion Rings',
    price: 5.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Burger Palace',
    description: 'Thick-cut onion rings in crispy beer batter, served with ranch dip.',
    rating: 4.3,
    reviews: 189,
    preparationTime: '10-12 min',
    isAvailable: true,
    tags: ['onion rings', 'crispy', 'beer batter'],
    ingredients: ['Onions', 'Beer Batter', 'Ranch Dressing'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 285,
      protein: 4,
      carbs: 38,
      fat: 14,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Regular',
  },
  {
    id: '60',
    name: 'Cheese Sticks',
    price: 7.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Bella Italia',
    description: 'Breaded mozzarella sticks served with marinara sauce for dipping.',
    rating: 4.4,
    reviews: 167,
    preparationTime: '8-10 min',
    isAvailable: true,
    tags: ['cheese', 'mozzarella', 'crispy'],
    ingredients: ['Mozzarella', 'Breadcrumbs', 'Marinara Sauce'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    nutritionalInfo: {
      calories: 320,
      protein: 16,
      carbs: 22,
      fat: 18,
      fiber: 1,
    },
    spiceLevel: 'mild',
    portionSize: '6 Sticks',
  },
  {
    id: '61',
    name: 'Trail Mix',
    price: 4.99,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    category: 'Snacks',
    restaurant: 'Green Bowl',
    description: 'Healthy mix of nuts, dried fruits, and dark chocolate pieces.',
    rating: 4.2,
    reviews: 123,
    preparationTime: '1-2 min',
    isAvailable: true,
    tags: ['healthy', 'nuts', 'energy'],
    ingredients: ['Almonds', 'Cashews', 'Dried Cranberries', 'Dark Chocolate'],
    allergens: ['Nuts'],
    nutritionalInfo: {
      calories: 185,
      protein: 6,
      carbs: 18,
      fat: 12,
      fiber: 3,
    },
    spiceLevel: 'mild',
    portionSize: 'Small Bag',
  },
];

const initialState: ProductsState = {
  items: mockProducts,
  restaurants: mockRestaurants,
  categories: [
    'Pizza', 'Indian', 'Sushi', 'Pasta', 'Burgers', 'Healthy', 'Desserts', 
    'Beverages', 'Appetizers', 'Snacks', 'Mexican', 'Seafood', 'Italian', 
    'Japanese', 'American', 'Mediterranean', 'Vegetarian', 'Vegan'
  ],
  featured: mockProducts.filter(p => p.isFeatured),
  trending: mockProducts.filter(p => p.isPopular),
  dailyDeals: mockProducts.filter(p => p.discount && p.discount > 10),
  flashSales: mockProducts.filter(p => p.discount && p.discount > 15),
  loading: false,
  searchQuery: '',
  filters: {
    priceRange: [0, 50],
    rating: 0,
    preparationTime: 60,
    spiceLevel: [],
    dietary: [],
  },
};

const productsSlice = createSlice({
  name: 'products',
  initialState,
  reducers: {
    setProducts: (state, action: PayloadAction<Product[]>) => {
      state.items = action.payload;
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload;
    },
    setSearchQuery: (state, action: PayloadAction<string>) => {
      state.searchQuery = action.payload;
    },
    setSelectedCategory: (state, action: PayloadAction<string | undefined>) => {
      state.selectedCategory = action.payload;
    },
    setFilters: (state, action: PayloadAction<Partial<ProductsState['filters']>>) => {
      state.filters = { ...state.filters, ...action.payload };
    },
    clearFilters: (state) => {
      state.filters = {
        priceRange: [0, 50],
        rating: 0,
        preparationTime: 60,
        spiceLevel: [],
        dietary: [],
      };
    },
  },
});

export const { 
  setProducts, 
  setLoading, 
  setSearchQuery, 
  setSelectedCategory, 
  setFilters, 
  clearFilters 
} = productsSlice.actions;
export default productsSlice.reducer;